project:
  type: website


format:
  html:
    page-layout: full
    toc: true
    code-fold: true
    theme: flatly
    code-tools: true
      

website:
  title: "AE8803: Machine Learning with Gaussian Processes"
  page-navigation: true
  navbar:
    background: secondary
    right:
      - icon: github
        href: https://github.com/psesh/ae8803
        aria-label: GitHub
  sidebar:
    title: "AE2010/11"
    search: true
    style: "docked"
    contents:
      - index.ipynb

