project:
  type: website
  output-dir: site
  render:
    - index.qmd
    - slides/lecture-5/index.qmd
    - slides/lecture-6/index.qmd
    - slides/lecture-7/index.qmd
    - slides/lecture-8/index.qmd
    - slides/lecture-9/index.qmd
    - slides/lecture-10/index.qmd
    - slides/lecture-12/index.qmd
    - sample_problems/lecture_1.qmd
    - sample_problems/lecture_2.qmd
    - sample_problems/lecture_3.qmd
    - sample_problems/lecture_4.qmd
    - useful_codes/discrete.qmd
    - useful_codes/gaussians.qmd
    - useful_codes/kernels.ipynb
    - useful_codes/eigen.ipynb
    - useful_codes/fourier.ipynb
    - useful_codes/gp101.ipynb
    - useful_codes/mcmc.ipynb
    - useful_codes/vi.ipynb
    - useful_codes/sparse.ipynb
    - coding-1/coding-1.ipynb
    - midterm/midterm_2024_solutions.ipynb
    - project/proposals_and_projects.ipynb
format:
  html:
    page-layout: full
    toc: true
    code-fold: true
    backgroundcolor: "#FDF1E6"
    theme: 
      light: [zephyr, main.scss]
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet">
    mainfont: "Playfair Display"
    linkcolor: "#8C213E"
    code-tools: true
    description-meta: Course website for AE8803 -- a graduate-level course on Gaussian processes.
    favicon: images/logo.ico
    keywords: pranay seshadri, machine learning, gaussian processes
    pagetitle: AE8803 | Georgia Institute of Technology

website:
  title: "AE8803: MACHINE LEARNING WITH GAUSSIAN PROCESSES"
  page-navigation: true
  navbar:
    background: secondary
    left:
      - text: "Home"
        href: https://psesh.github.io/ae8803/
      - text: "Canvas"
        href: https://canvas.gatech.edu
    right:
      - icon: github
        href: https://github.com/psesh/ae8803
        aria-label: GitHub
  sidebar:
    search: true
    style: "docked"
    contents:
      - section: "Examples"
        contents:
              - text: "L1"
                href: https://psesh.github.io/ae8803/sample_problems/lecture_1.html
              - text: "L2"
                href: https://psesh.github.io/ae8803/sample_problems/lecture_2.html
              - text: "L3"
                href: https://psesh.github.io/ae8803/sample_problems/lecture_3.html
              - text: "L4"
                href: https://psesh.github.io/ae8803/sample_problems/lecture_4.html
      - section: "Notebooks"
        contents:
          - text: "Discrete distributions"
            href: https://psesh.github.io/ae8803/useful_codes/discrete.html
          - text: "Marginal and conditional Gaussians"
            href: https://psesh.github.io/ae8803/useful_codes/gaussians.html
          - text: "Kernel trick and lifting"
            href: https://psesh.github.io/ae8803/useful_codes/kernels.html
          - text: "Eigenfunction analysis of kernels"
            href: https://psesh.github.io/ae8803/useful_codes/eigen.html
          - text: "Fourier analysis of kernels"
            href: https://psesh.github.io/ae8803/useful_codes/fourier.html
          - text: "GP 101"
            href: https://psesh.github.io/ae8803/useful_codes/gp101.html
          - text: "Inference with MAP & MCMC"
            href: https://psesh.github.io/ae8803/useful_codes/mcmc.html
          - text: "Variational inference"
            href: https://psesh.github.io/ae8803/useful_codes/vi.html
          - text: "Sparse Gaussian processes"
            href: https://psesh.github.io/ae8803/useful_codes/sparse.html
      - section: "Assignments"
        contents:
              - text: "Assignment 2"
                href: https://psesh.github.io/ae8803/coding-1/coding-1.html
              - text: "Assignment 3"
                href: https://psesh.github.io/ae8803/project/proposals_and_projects.html
#   
# freeze: false