project:
  type: website
  output-dir: site
  render:
    - index.qmd
    - slides/lecture-5/index.qmd
    - slides/lecture-6/index.qmd
    - sample_problems/lecture_1.ipynb
    - sample_problems/lecture_2.ipynb
    - sample_problems/lecture_3.ipynb
    - sample_problems/lecture_4.ipynb
    - useful_codes/discrete.ipynb
format:
  html:
    page-layout: full
    toc: true
    code-fold: true
    theme: flatly
    code-tools: true
    description-meta: Course website for AE8803 that comprises fluid fundamentals and thermodynamics. It can be taken either as a 3-credit course (without thermodynamics) or as a 4-credit course (with thermodynamics). It is a mandatory course for all aerospace engineering students. 
    favicon: images/logo.ico
    keywords: pranay seshadri, machine learning, gaussian processes
    pagetitle: AE8803 | Georgia Institute of Technology

website:
  title: "AE8803: Machine Learning with Gaussian Processes"
  page-navigation: true
  navbar:
    background: secondary
    left:
      - text: "Home"
        href: https://psesh.github.io/ae8803/
      - text: "Canvas"
        href: https://canvas.gatech.edu
    right:
      - icon: github
        href: https://github.com/psesh/ae8803
        aria-label: GitHub
  sidebar:
    search: true
    style: "docked"
    contents:
      - section: "Examples"
        contents:
              - text: "L1"
                href: https://github.com/psesh/ae8803/sample_problems/lecture_1.html
              - text: "L2"
                href: https://github.com/psesh/ae8803/sample_problems/lecture_2.html
              - text: "L3"
                href: https://github.com/psesh/ae8803/sample_problems/lecture_3.html
              - text: "L4"
                href: https://github.com/psesh/ae8803/sample_problems/lecture_4.html
      - section: "Utilities"
        contents:
          - text: "Useful codes"
            href: https://github.com/psesh/ae8803/useful_codes/discrete.html
# 
# freeze: false